export const ADD_USER = "ADD_USER";
export const ADD_USER_OK = "ADD_USER_OK";
export const ADD_USER_ERROR = "ADD_USER_ERROR";

export const START_DOWNLOAD_ORDERS = "START_DOWNLOAD_ORDERS";
export const START_DOWNLOAD_ORDERS_OK = "START_DOWNLOAD_ORDERS_OK";
export const START_DOWNLOAD_ORDERS_ERROR = "START_DOWNLOAD_ORDERS_OK";

export const FIND_ORDER = "FIND_ORDER";

export const SHOW_ALERT = "[UI] SHOW_ALERT";
export const HIDE_ALERT = "[UI] HIDE_ALERT";
export const START_LOADING = "[UI] START_LOADING";
export const FINISH_LOADING = "[UI] FINISH_LOADING";

export const LOGIN = "[Auth] LOGIN";
export const LOGOUT = "[Auth] LOGOUT";

export const ADD_CATEGORY = "ADD_CATEGORY"
export const ADD_CATEGORY_ERROR = "ADD_CATEGORY_ERROR"

export const RESULT_THE_THING = 'RESULT_THE_THING'
export const RESULT_THE_THING_OK = 'RESULT_THE_THING_OK'
export const RESULT_THE_THING_ERROR = 'RESULT_THE_THING_ERROR'

export const SET_COLORS = 'SET_COLORS'
